name: Windows

on:
  push:
    branches: [ cmake ]
  pull_request:
    branches: [ cmake ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: mingw build
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-libjpeg-turbo
          unzip

    - name: ffmpeg -- download
      run: git clone --depth 1 --branch n4.3.6 https://git.ffmpeg.org/ffmpeg.git ffmpeg
    - name: ffmpeg -- configure
      run: ./configure
        --prefix=ffmpeg-build
        --disable-programs
        --disable-doc
        --disable-avdevice
        --disable-avfilter
        --disable-network
        --disable-pixelutils
        --disable-everything
        --enable-decoder=pcm-s16le
        --enable-demuxer=wav
        --enable-protocol=file
      working-directory: ffmpeg
    - name: ffmpeg -- build and install
      run: |
        make
        make install
        mkdir -p ${{github.workspace}}/3rdparty/FFmpeg-n4.3.6
        cp -r ffmpeg-build/include ${{github.workspace}}/3rdparty/FFmpeg-n4.3.6/
        cp -r ffmpeg-build/lib ${{github.workspace}}/3rdparty/FFmpeg-n4.3.6/
      working-directory: ffmpeg

    - shell: msys2 {0}
      run: |
        mkdir build-mingw
        cd build-mingw
        cmake -G "Unix Makefiles" ..
        make -j4
        cd ..
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: Mechosoma
        path: |
          build-mingw/MechoSoma/moonshine-runners.exe
          build-mingw/MechoSoma/*.dll
